//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantDocente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public int DocenteId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public string NroDocumento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Estado { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
